on:
  push:
    branches:
      - main
      
name: Groupe4-workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
        
        # login to Azure
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        # login to ACR
        - name: 'Login to ACR'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        

        # deploy to ACA
        - name: Build and deploy Container App
          uses: azure/container-apps-deploy-action@v0
          with:
            containerAppName: classifier_g4
            resourceGroup: ${{ secrets.RESOURCE_GROUP }}
            imageToDeploy: ${{ secrets.REGISTRY_LOGIN_SERVER }}/classifier_g${{ secrets.GROUPE }}:v1
