on:
  push:
    branches:
      - main
      
name: Groupe4-workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
        
        # login to Azure
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        # login to ACR
        - name: 'Login to ACR'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        
        - name: Deploy to containerapp
          uses: azure/CLI@v1
          with:
            inlineScript: |
              az config set extension.use_dynamic_install=yes_without_prompt
              az containerapp registry set 
                -n classifier_g4 \
                -g ${{ secrets.RESOURCE_GROUP }} \
                --server ${{ secrets.REGISTRY_LOGIN_SERVER }} \
                --username  ${{ secrets.TASKSMANAGER_REGISTRY_USERNAME }} \
                --password ${{ secrets.TASKSMANAGER_REGISTRY_PASSWORD }}

              az containerapp update 
                -n classifier_g4 \
                -g ${{ secrets.RESOURCE_GROUP }} \
                --image ${{ secrets.REGISTRY_LOGIN_SERVER }}/classifier_g${{ secrets.GROUPE }}:v1

